name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#       - name: Build MySQL Docker image
#         run: docker build -t mysql-image -f Dockerfile_mysql .

#       - name: Build application Docker image
#         run: docker build -t app-image -f Dockerfile .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 232901375965.dkr.ecr.us-east-1.amazonaws.com

#       - name: Tag and push MySQL Docker image to ECR
#         run: |
#           docker tag mysql-image $ECR_REGISTRY/my-ecr-repo/mysql-image:${{ github.sha }}
#           docker push $ECR_REGISTRY/my-ecr-repo/mysql-image:${{ github.sha }}

#       - name: Tag and push application Docker image to ECR
#         run: |
#           docker tag app-image $ECR_REGISTRY/my-ecr-repo/app-image:${{ github.sha }}
#           docker push $ECR_REGISTRY/my-ecr-repo/app-image:${{ github.sha }}
